# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-07 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painter', '0005_card_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataFile',
        ),
    ]
